Crmagic/Crmagic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('webapp.urls', 'webapp'), namespace='webapp')),
]

Crmagic/webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.register_user, name='register_user'),
    path('record/<int:pk>', views.customer_record, name='c_record'),
    path('delete_record/<int:pk>', views.delete_record, name='d_record'),
    path('add_record/', views.add_record, name='add_record'),
    path('update_record/<int:pk>', views.update_record, name='u_record'),
]

Crmagic/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.


class Record(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    zipcode = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (f'{self.first_name} {self.last_name}')

Crmagic/webapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'First Name', 'class': 'form-control'}), label="")
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Last Name', 'class': 'form-control'}), label="")
    email = forms.EmailField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Email', 'class': 'form-control'}), label="")
    address = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Address', 'class': 'form-control'}), label="")
    phone = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Phone Number', 'class': 'form-control'}), label="")
    city = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'City', 'class': 'form-control'}), label="")
    state = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'State', 'class': 'form-control'}), label="")
    zipcode = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Zip-Code', 'class': 'form-control'}), label="")

    class Meta:
        model = Record
        exclude = ("user, ",)
        fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'city', 'state', 'zipcode']

Crmagic/webapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, AddRecordForm
from .models import Record
# Create your views here.


@login_required(login_url='webapp:login_user')
def home(request):
    records = Record.objects.filter(creator=request.user)
    return render(request, 'home.html', {'records': records})


def login_user(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('webapp:home')
        print('not here')
        messages.success(request, 'Username or Password is incorrect')
        return render(request, 'login.html')
    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    messages.success(request, 'You are now logged out')
    return redirect('webapp:login_user')


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate and login
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(
                request, "You Have Successfully Registered! Welcome!")
            return redirect('webapp:home')
    else:
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})

    return render(request, 'register.html', {'form': form})


@login_required(login_url='webapp:login_user')
def customer_record(request, pk):
    customer_record = Record.objects.get(id=pk)
    return render(request, 'c_record.html', {'customer_record': customer_record})


@login_required(login_url='webapp:login_user')
def delete_record(request, pk):
    delete_it = Record.objects.get(id=pk)
    delete_it.delete()
    messages.success(request, 'Record Deleted Successfully')
    return redirect('webapp:home')


@login_required(login_url='webapp:login_user')
def add_record(request):
    form = AddRecordForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            add_record = form.save(commit=False)
            add_record.creator = request.user
            add_record.save()
            messages.success(request, "Record Added Successfully")
            return redirect('webapp:home')
    return render(request, 'add_record.html', {'form': form})


@login_required(login_url='webapp:login_user')
def update_record(request, pk):
    current_record = Record.objects.get(id=pk)
    form = AddRecordForm(request.POST or None, instance=current_record)
    if form.is_valid():
        form.save()
        messages.success(request, "Record Updated Successfully")
        return redirect('webapp:home')
    return render(request, 'update_record.html', {'form': form})

Crmagic/webapp/templates/add_record.html
{% extends 'base.html' %}

{% block title %}
    Add Record
{% endblock %}


{% block content %}

<div class="col-md-6 offset-md-3">
    <br>
    <h1>Add Record </h1>
    <form method="post" action="">
        {% csrf_token %}

        {{form.as_p}}
<br>
	  <button type="submit" class="btn btn-danger">Register</button>
       <a href="{% url 'webapp:home' %}" class="btn btn-primary">Back</a>
    </form>

</div>
{% endblock %}

Crmagic/webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        
        {% if messages %}
        
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
        {% endfor %}
            
            
        {% endif %}
            
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

Crmagic/webapp/templates/c_record.html
{% extends 'base.html' %}

{% block title %}
    Customer record
{% endblock %}


{% block content %}
<br>


<div class="card">
  <div class="card-header">
   <strong> {{customer_record.first_name}} {{customer_record.last_name}}</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong>Phone Number: </strong>{{customer_record.phone}}</h5>
    <h5 class="card-title"><strong>Address: </strong>{{customer_record.address}}</h5>
    <h5 class="card-title"><strong>City: </strong>{{customer_record.city}}</h5>
    <h5 class="card-title"><strong>State: </strong>{{customer_record.state}}</h5>
    <h5 class="card-title"><strong>Zipcode: </strong>{{customer_record.zipcode}}</h5>
    <h5 class="card-title"><strong>Created At: </strong>{{customer_record.created_at}}</h5>
    <h5 class="card-title"><strong>Last Update: </strong>{{customer_record.updated_at}}</h5>
    <h5 class="card-title"><strong>ID: </strong>{{customer_record.id}}</h5>
    
  </div>
</div>
<br> 
<a href="{% url 'webapp:home' %}" class="btn btn-secondary">Back</a>
<a href="{% url 'webapp:d_record' pk=customer_record.id%}" class="btn btn-danger">Delete</a>
<a href="{% url 'webapp:u_record' pk=customer_record.id%}" class="btn btn-primary">Update</a>







{% endblock %}

Crmagic/webapp/templates/home.html
{% extends 'base.html' %} {% block title %} Homepage {% endblock%} 
{% block content %}
<br>
{% if user.is_authenticated %}
    
<table class="table table-hover table-strped table-primary table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Zip-code</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Created At</th>
      <th scope="col">ID</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    
{% if records %}
    {% for record in records  %}
    <tr>
      <td>{{record.first_name}}
      {{record.last_name}}</td>
      <td>{{record.email}}</td>
      <td>{{record.phone}}</td>
      <td>{{record.address}}</td>
      <td>{{record.zipcode}}</td>
      <td>{{record.city}}</td>
      <td>{{record.state}}</td>
      <td>{{record.created_at}}</td>
      <td><a href="{% url 'webapp:c_record' pk=record.id %}">{{record.id}}</a></td>
    {% endfor %}
</tr>
        
{% endif %}
  </tbody>
</table>



    {% endif %}
{% endblock%}

Crmagic/webapp/templates/login.html
{% extends 'base.html' %} {% block title %} Login {% endblock %} 
{% block content %}
<div class="col-md-6 offset-md-3">
  <h1>LOGIN</h1>
  <br />
  <form class="login-form" method="post">
    {% csrf_token %}

    <div class="mb-3">
      <input
        type="text"
        class="form-control"
        placeholder="username"
        name="username"
        required
      />
    </div>
    <div class="mb-3">
      <input
        type="password"
        class="form-control"
        name="password"
        placeholder="password"
        required
      />
    </div>
    <button for="login-form" type="submit" class="btn btn-secondary">
      Login
    </button>
  </form>
</div>

{% endblock %}

Crmagic/webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CRMagic</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
            <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:add_record' %}">Add Record</a>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:logout_user' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:register_user' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:login_user' %}">Login</a>
        </li>
        {% endif %}
      </ul>
      
    </div>
  </div>
</nav>

Crmagic/webapp/templates/register.html
{% extends 'base.html' %}

{% block title %}
	Register
{% endblock %}
	
{% block content %}


<div class="col-md-6 offset-md-3">
<h1>Register</h1>
<br/>

<form method="POST" action="">
	
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-secondary">Register</button>
	</form>



</div>

{% endblock %}

Crmagic/webapp/templates/update_record.html
{% extends 'base.html' %}

{% block title %}
    Update record
{% endblock %}


{% block content %}
    

<div class="col-md-6 offset-md-3">
    <br>
    <h1>Update Record </h1>
    <form method="post" action="">
        {% csrf_token %}

        {{form.as_p}}
<br>
	  <button type="submit" class="btn btn-danger">Update</button>
      <a href="{% url 'webapp:home' %}" class="btn btn-primary">Back</a>
    </form>

</div>

{% endblock %}